#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.PiggySave.DA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbPiggySave")]
	public partial class dbPiggySaveDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBanco(Banco instance);
    partial void UpdateBanco(Banco instance);
    partial void DeleteBanco(Banco instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertMoneda(Moneda instance);
    partial void UpdateMoneda(Moneda instance);
    partial void DeleteMoneda(Moneda instance);
    partial void InsertMovimiento(Movimiento instance);
    partial void UpdateMovimiento(Movimiento instance);
    partial void DeleteMovimiento(Movimiento instance);
    partial void InsertTarjeta(Tarjeta instance);
    partial void UpdateTarjeta(Tarjeta instance);
    partial void DeleteTarjeta(Tarjeta instance);
    partial void InsertTarjetaXUsuario(TarjetaXUsuario instance);
    partial void UpdateTarjetaXUsuario(TarjetaXUsuario instance);
    partial void DeleteTarjetaXUsuario(TarjetaXUsuario instance);
    partial void InsertTransaccion(Transaccion instance);
    partial void UpdateTransaccion(Transaccion instance);
    partial void DeleteTransaccion(Transaccion instance);
    partial void InsertExcepcion(Excepcion instance);
    partial void UpdateExcepcion(Excepcion instance);
    partial void DeleteExcepcion(Excepcion instance);
    #endregion
		
		public dbPiggySaveDataContext() : 
				base(global::UPC.PiggySave.DA.Properties.Settings.Default.dbPiggySaveConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbPiggySaveDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbPiggySaveDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbPiggySaveDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbPiggySaveDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Banco> Bancos
		{
			get
			{
				return this.GetTable<Banco>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Moneda> Monedas
		{
			get
			{
				return this.GetTable<Moneda>();
			}
		}
		
		public System.Data.Linq.Table<Movimiento> Movimientos
		{
			get
			{
				return this.GetTable<Movimiento>();
			}
		}
		
		public System.Data.Linq.Table<Tarjeta> Tarjetas
		{
			get
			{
				return this.GetTable<Tarjeta>();
			}
		}
		
		public System.Data.Linq.Table<TarjetaXUsuario> TarjetaXUsuarios
		{
			get
			{
				return this.GetTable<TarjetaXUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Transaccion> Transaccions
		{
			get
			{
				return this.GetTable<Transaccion>();
			}
		}
		
		public System.Data.Linq.Table<Excepcion> Excepcions
		{
			get
			{
				return this.GetTable<Excepcion>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Banco")]
	public partial class Banco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBanco;
		
		private string _nombre;
		
		private string _abreviatura;
		
		private int _idUsuarioRegistro;
		
		private System.DateTime _fechaRegistro;
		
		private System.Nullable<int> _idUsuarioModifico;
		
		private System.Nullable<System.DateTime> _fechaModifico;
		
		private bool _activo;
		
		private EntitySet<Tarjeta> _Tarjetas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBancoChanging(int value);
    partial void OnidBancoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnabreviaturaChanging(string value);
    partial void OnabreviaturaChanged();
    partial void OnidUsuarioRegistroChanging(int value);
    partial void OnidUsuarioRegistroChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    partial void OnidUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnidUsuarioModificoChanged();
    partial void OnfechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaModificoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public Banco()
		{
			this._Tarjetas = new EntitySet<Tarjeta>(new Action<Tarjeta>(this.attach_Tarjetas), new Action<Tarjeta>(this.detach_Tarjetas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBanco", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idBanco
		{
			get
			{
				return this._idBanco;
			}
			set
			{
				if ((this._idBanco != value))
				{
					this.OnidBancoChanging(value);
					this.SendPropertyChanging();
					this._idBanco = value;
					this.SendPropertyChanged("idBanco");
					this.OnidBancoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abreviatura", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string abreviatura
		{
			get
			{
				return this._abreviatura;
			}
			set
			{
				if ((this._abreviatura != value))
				{
					this.OnabreviaturaChanging(value);
					this.SendPropertyChanging();
					this._abreviatura = value;
					this.SendPropertyChanged("abreviatura");
					this.OnabreviaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioRegistro", DbType="Int NOT NULL")]
		public int idUsuarioRegistro
		{
			get
			{
				return this._idUsuarioRegistro;
			}
			set
			{
				if ((this._idUsuarioRegistro != value))
				{
					this.OnidUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioRegistro = value;
					this.SendPropertyChanged("idUsuarioRegistro");
					this.OnidUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioModifico", DbType="Int")]
		public System.Nullable<int> idUsuarioModifico
		{
			get
			{
				return this._idUsuarioModifico;
			}
			set
			{
				if ((this._idUsuarioModifico != value))
				{
					this.OnidUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioModifico = value;
					this.SendPropertyChanged("idUsuarioModifico");
					this.OnidUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaModifico
		{
			get
			{
				return this._fechaModifico;
			}
			set
			{
				if ((this._fechaModifico != value))
				{
					this.OnfechaModificoChanging(value);
					this.SendPropertyChanging();
					this._fechaModifico = value;
					this.SendPropertyChanged("fechaModifico");
					this.OnfechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Banco_Tarjeta", Storage="_Tarjetas", ThisKey="idBanco", OtherKey="idBanco")]
		public EntitySet<Tarjeta> Tarjetas
		{
			get
			{
				return this._Tarjetas;
			}
			set
			{
				this._Tarjetas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Banco = this;
		}
		
		private void detach_Tarjetas(Tarjeta entity)
		{
			this.SendPropertyChanging();
			entity.Banco = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private string _nombre;
		
		private string _apellido;
		
		private string _email;
		
		private string _contrasena;
		
		private int _idUsuarioRegistro;
		
		private System.DateTime _fechaRegistro;
		
		private System.Nullable<int> _idUsuarioModifico;
		
		private System.Nullable<System.DateTime> _fechaModifico;
		
		private bool _activo;
		
		private EntitySet<TarjetaXUsuario> _TarjetaXUsuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    partial void OnidUsuarioRegistroChanging(int value);
    partial void OnidUsuarioRegistroChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    partial void OnidUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnidUsuarioModificoChanged();
    partial void OnfechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaModificoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public Usuario()
		{
			this._TarjetaXUsuarios = new EntitySet<TarjetaXUsuario>(new Action<TarjetaXUsuario>(this.attach_TarjetaXUsuarios), new Action<TarjetaXUsuario>(this.detach_TarjetaXUsuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioRegistro", DbType="Int NOT NULL")]
		public int idUsuarioRegistro
		{
			get
			{
				return this._idUsuarioRegistro;
			}
			set
			{
				if ((this._idUsuarioRegistro != value))
				{
					this.OnidUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioRegistro = value;
					this.SendPropertyChanged("idUsuarioRegistro");
					this.OnidUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioModifico", DbType="Int")]
		public System.Nullable<int> idUsuarioModifico
		{
			get
			{
				return this._idUsuarioModifico;
			}
			set
			{
				if ((this._idUsuarioModifico != value))
				{
					this.OnidUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioModifico = value;
					this.SendPropertyChanged("idUsuarioModifico");
					this.OnidUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaModifico
		{
			get
			{
				return this._fechaModifico;
			}
			set
			{
				if ((this._fechaModifico != value))
				{
					this.OnfechaModificoChanging(value);
					this.SendPropertyChanging();
					this._fechaModifico = value;
					this.SendPropertyChanged("fechaModifico");
					this.OnfechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_TarjetaXUsuario", Storage="_TarjetaXUsuarios", ThisKey="idUsuario", OtherKey="idUsuario")]
		public EntitySet<TarjetaXUsuario> TarjetaXUsuarios
		{
			get
			{
				return this._TarjetaXUsuarios;
			}
			set
			{
				this._TarjetaXUsuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TarjetaXUsuarios(TarjetaXUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_TarjetaXUsuarios(TarjetaXUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Moneda")]
	public partial class Moneda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMoneda;
		
		private string _nombre;
		
		private string _abreviatura;
		
		private int _idUsuarioRegistro;
		
		private System.DateTime _fechaRegistro;
		
		private System.Nullable<int> _idUsuarioModifico;
		
		private System.Nullable<System.DateTime> _fechaModifico;
		
		private bool _activo;
		
		private EntitySet<Movimiento> _Movimientos;
		
		private EntitySet<Transaccion> _Transaccions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMonedaChanging(int value);
    partial void OnidMonedaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnabreviaturaChanging(string value);
    partial void OnabreviaturaChanged();
    partial void OnidUsuarioRegistroChanging(int value);
    partial void OnidUsuarioRegistroChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    partial void OnidUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnidUsuarioModificoChanged();
    partial void OnfechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaModificoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public Moneda()
		{
			this._Movimientos = new EntitySet<Movimiento>(new Action<Movimiento>(this.attach_Movimientos), new Action<Movimiento>(this.detach_Movimientos));
			this._Transaccions = new EntitySet<Transaccion>(new Action<Transaccion>(this.attach_Transaccions), new Action<Transaccion>(this.detach_Transaccions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMoneda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMoneda
		{
			get
			{
				return this._idMoneda;
			}
			set
			{
				if ((this._idMoneda != value))
				{
					this.OnidMonedaChanging(value);
					this.SendPropertyChanging();
					this._idMoneda = value;
					this.SendPropertyChanged("idMoneda");
					this.OnidMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abreviatura", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string abreviatura
		{
			get
			{
				return this._abreviatura;
			}
			set
			{
				if ((this._abreviatura != value))
				{
					this.OnabreviaturaChanging(value);
					this.SendPropertyChanging();
					this._abreviatura = value;
					this.SendPropertyChanged("abreviatura");
					this.OnabreviaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioRegistro", DbType="Int NOT NULL")]
		public int idUsuarioRegistro
		{
			get
			{
				return this._idUsuarioRegistro;
			}
			set
			{
				if ((this._idUsuarioRegistro != value))
				{
					this.OnidUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioRegistro = value;
					this.SendPropertyChanged("idUsuarioRegistro");
					this.OnidUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioModifico", DbType="Int")]
		public System.Nullable<int> idUsuarioModifico
		{
			get
			{
				return this._idUsuarioModifico;
			}
			set
			{
				if ((this._idUsuarioModifico != value))
				{
					this.OnidUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioModifico = value;
					this.SendPropertyChanged("idUsuarioModifico");
					this.OnidUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaModifico
		{
			get
			{
				return this._fechaModifico;
			}
			set
			{
				if ((this._fechaModifico != value))
				{
					this.OnfechaModificoChanging(value);
					this.SendPropertyChanging();
					this._fechaModifico = value;
					this.SendPropertyChanged("fechaModifico");
					this.OnfechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Moneda_Movimiento", Storage="_Movimientos", ThisKey="idMoneda", OtherKey="idMoneda")]
		public EntitySet<Movimiento> Movimientos
		{
			get
			{
				return this._Movimientos;
			}
			set
			{
				this._Movimientos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Moneda_Transaccion", Storage="_Transaccions", ThisKey="idMoneda", OtherKey="idMoneda")]
		public EntitySet<Transaccion> Transaccions
		{
			get
			{
				return this._Transaccions;
			}
			set
			{
				this._Transaccions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Movimientos(Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.Moneda = this;
		}
		
		private void detach_Movimientos(Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.Moneda = null;
		}
		
		private void attach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Moneda = this;
		}
		
		private void detach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.Moneda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movimiento")]
	public partial class Movimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idMovimiento;
		
		private int _idTransaccion;
		
		private int _periodoFacturacion;
		
		private int _numeroCuota;
		
		private int _idMoneda;
		
		private decimal _monto;
		
		private int _idUsuarioRegistro;
		
		private System.DateTime _fechaRegistro;
		
		private System.Nullable<int> _idUsuarioModifico;
		
		private System.Nullable<System.DateTime> _fechaModifico;
		
		private bool _activo;
		
		private EntityRef<Moneda> _Moneda;
		
		private EntityRef<Transaccion> _Transaccion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidMovimientoChanging(int value);
    partial void OnidMovimientoChanged();
    partial void OnidTransaccionChanging(int value);
    partial void OnidTransaccionChanged();
    partial void OnperiodoFacturacionChanging(int value);
    partial void OnperiodoFacturacionChanged();
    partial void OnnumeroCuotaChanging(int value);
    partial void OnnumeroCuotaChanged();
    partial void OnidMonedaChanging(int value);
    partial void OnidMonedaChanged();
    partial void OnmontoChanging(decimal value);
    partial void OnmontoChanged();
    partial void OnidUsuarioRegistroChanging(int value);
    partial void OnidUsuarioRegistroChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    partial void OnidUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnidUsuarioModificoChanged();
    partial void OnfechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaModificoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public Movimiento()
		{
			this._Moneda = default(EntityRef<Moneda>);
			this._Transaccion = default(EntityRef<Transaccion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMovimiento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idMovimiento
		{
			get
			{
				return this._idMovimiento;
			}
			set
			{
				if ((this._idMovimiento != value))
				{
					this.OnidMovimientoChanging(value);
					this.SendPropertyChanging();
					this._idMovimiento = value;
					this.SendPropertyChanged("idMovimiento");
					this.OnidMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTransaccion", DbType="Int NOT NULL")]
		public int idTransaccion
		{
			get
			{
				return this._idTransaccion;
			}
			set
			{
				if ((this._idTransaccion != value))
				{
					if (this._Transaccion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTransaccionChanging(value);
					this.SendPropertyChanging();
					this._idTransaccion = value;
					this.SendPropertyChanged("idTransaccion");
					this.OnidTransaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_periodoFacturacion", DbType="Int NOT NULL")]
		public int periodoFacturacion
		{
			get
			{
				return this._periodoFacturacion;
			}
			set
			{
				if ((this._periodoFacturacion != value))
				{
					this.OnperiodoFacturacionChanging(value);
					this.SendPropertyChanging();
					this._periodoFacturacion = value;
					this.SendPropertyChanged("periodoFacturacion");
					this.OnperiodoFacturacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroCuota", DbType="Int NOT NULL")]
		public int numeroCuota
		{
			get
			{
				return this._numeroCuota;
			}
			set
			{
				if ((this._numeroCuota != value))
				{
					this.OnnumeroCuotaChanging(value);
					this.SendPropertyChanging();
					this._numeroCuota = value;
					this.SendPropertyChanged("numeroCuota");
					this.OnnumeroCuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMoneda", DbType="Int NOT NULL")]
		public int idMoneda
		{
			get
			{
				return this._idMoneda;
			}
			set
			{
				if ((this._idMoneda != value))
				{
					if (this._Moneda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMonedaChanging(value);
					this.SendPropertyChanging();
					this._idMoneda = value;
					this.SendPropertyChanged("idMoneda");
					this.OnidMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="Decimal(18,2) NOT NULL")]
		public decimal monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioRegistro", DbType="Int NOT NULL")]
		public int idUsuarioRegistro
		{
			get
			{
				return this._idUsuarioRegistro;
			}
			set
			{
				if ((this._idUsuarioRegistro != value))
				{
					this.OnidUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioRegistro = value;
					this.SendPropertyChanged("idUsuarioRegistro");
					this.OnidUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioModifico", DbType="Int")]
		public System.Nullable<int> idUsuarioModifico
		{
			get
			{
				return this._idUsuarioModifico;
			}
			set
			{
				if ((this._idUsuarioModifico != value))
				{
					this.OnidUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioModifico = value;
					this.SendPropertyChanged("idUsuarioModifico");
					this.OnidUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaModifico
		{
			get
			{
				return this._fechaModifico;
			}
			set
			{
				if ((this._fechaModifico != value))
				{
					this.OnfechaModificoChanging(value);
					this.SendPropertyChanging();
					this._fechaModifico = value;
					this.SendPropertyChanged("fechaModifico");
					this.OnfechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Moneda_Movimiento", Storage="_Moneda", ThisKey="idMoneda", OtherKey="idMoneda", IsForeignKey=true)]
		public Moneda Moneda
		{
			get
			{
				return this._Moneda.Entity;
			}
			set
			{
				Moneda previousValue = this._Moneda.Entity;
				if (((previousValue != value) 
							|| (this._Moneda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Moneda.Entity = null;
						previousValue.Movimientos.Remove(this);
					}
					this._Moneda.Entity = value;
					if ((value != null))
					{
						value.Movimientos.Add(this);
						this._idMoneda = value.idMoneda;
					}
					else
					{
						this._idMoneda = default(int);
					}
					this.SendPropertyChanged("Moneda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaccion_Movimiento", Storage="_Transaccion", ThisKey="idTransaccion", OtherKey="idTransaccion", IsForeignKey=true)]
		public Transaccion Transaccion
		{
			get
			{
				return this._Transaccion.Entity;
			}
			set
			{
				Transaccion previousValue = this._Transaccion.Entity;
				if (((previousValue != value) 
							|| (this._Transaccion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Transaccion.Entity = null;
						previousValue.Movimientos.Remove(this);
					}
					this._Transaccion.Entity = value;
					if ((value != null))
					{
						value.Movimientos.Add(this);
						this._idTransaccion = value.idTransaccion;
					}
					else
					{
						this._idTransaccion = default(int);
					}
					this.SendPropertyChanged("Transaccion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tarjeta")]
	public partial class Tarjeta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTarjeta;
		
		private string _nombre;
		
		private int _idBanco;
		
		private int _idUsuarioRegistro;
		
		private System.DateTime _fechaRegistro;
		
		private System.Nullable<int> _idUsuarioModifico;
		
		private System.Nullable<System.DateTime> _fechaModifico;
		
		private bool _activo;
		
		private EntitySet<TarjetaXUsuario> _TarjetaXUsuarios;
		
		private EntityRef<Banco> _Banco;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTarjetaChanging(int value);
    partial void OnidTarjetaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnidBancoChanging(int value);
    partial void OnidBancoChanged();
    partial void OnidUsuarioRegistroChanging(int value);
    partial void OnidUsuarioRegistroChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    partial void OnidUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnidUsuarioModificoChanged();
    partial void OnfechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaModificoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public Tarjeta()
		{
			this._TarjetaXUsuarios = new EntitySet<TarjetaXUsuario>(new Action<TarjetaXUsuario>(this.attach_TarjetaXUsuarios), new Action<TarjetaXUsuario>(this.detach_TarjetaXUsuarios));
			this._Banco = default(EntityRef<Banco>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTarjeta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTarjeta
		{
			get
			{
				return this._idTarjeta;
			}
			set
			{
				if ((this._idTarjeta != value))
				{
					this.OnidTarjetaChanging(value);
					this.SendPropertyChanging();
					this._idTarjeta = value;
					this.SendPropertyChanged("idTarjeta");
					this.OnidTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBanco", DbType="Int NOT NULL")]
		public int idBanco
		{
			get
			{
				return this._idBanco;
			}
			set
			{
				if ((this._idBanco != value))
				{
					if (this._Banco.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidBancoChanging(value);
					this.SendPropertyChanging();
					this._idBanco = value;
					this.SendPropertyChanged("idBanco");
					this.OnidBancoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioRegistro", DbType="Int NOT NULL")]
		public int idUsuarioRegistro
		{
			get
			{
				return this._idUsuarioRegistro;
			}
			set
			{
				if ((this._idUsuarioRegistro != value))
				{
					this.OnidUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioRegistro = value;
					this.SendPropertyChanged("idUsuarioRegistro");
					this.OnidUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioModifico", DbType="Int")]
		public System.Nullable<int> idUsuarioModifico
		{
			get
			{
				return this._idUsuarioModifico;
			}
			set
			{
				if ((this._idUsuarioModifico != value))
				{
					this.OnidUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioModifico = value;
					this.SendPropertyChanged("idUsuarioModifico");
					this.OnidUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaModifico
		{
			get
			{
				return this._fechaModifico;
			}
			set
			{
				if ((this._fechaModifico != value))
				{
					this.OnfechaModificoChanging(value);
					this.SendPropertyChanging();
					this._fechaModifico = value;
					this.SendPropertyChanged("fechaModifico");
					this.OnfechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tarjeta_TarjetaXUsuario", Storage="_TarjetaXUsuarios", ThisKey="idTarjeta", OtherKey="idTarjeta")]
		public EntitySet<TarjetaXUsuario> TarjetaXUsuarios
		{
			get
			{
				return this._TarjetaXUsuarios;
			}
			set
			{
				this._TarjetaXUsuarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Banco_Tarjeta", Storage="_Banco", ThisKey="idBanco", OtherKey="idBanco", IsForeignKey=true)]
		public Banco Banco
		{
			get
			{
				return this._Banco.Entity;
			}
			set
			{
				Banco previousValue = this._Banco.Entity;
				if (((previousValue != value) 
							|| (this._Banco.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Banco.Entity = null;
						previousValue.Tarjetas.Remove(this);
					}
					this._Banco.Entity = value;
					if ((value != null))
					{
						value.Tarjetas.Add(this);
						this._idBanco = value.idBanco;
					}
					else
					{
						this._idBanco = default(int);
					}
					this.SendPropertyChanged("Banco");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TarjetaXUsuarios(TarjetaXUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Tarjeta = this;
		}
		
		private void detach_TarjetaXUsuarios(TarjetaXUsuario entity)
		{
			this.SendPropertyChanging();
			entity.Tarjeta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TarjetaXUsuario")]
	public partial class TarjetaXUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idUsuario;
		
		private int _idTarjeta;
		
		private string _numero;
		
		private int _diaCierre;
		
		private int _idUsuarioRegistro;
		
		private System.DateTime _fechaRegistro;
		
		private System.Nullable<int> _idUsuarioModifico;
		
		private System.Nullable<System.DateTime> _fechaModifico;
		
		private bool _activo;
		
		private EntitySet<Transaccion> _Transaccions;
		
		private EntityRef<Tarjeta> _Tarjeta;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnidTarjetaChanging(int value);
    partial void OnidTarjetaChanged();
    partial void OnnumeroChanging(string value);
    partial void OnnumeroChanged();
    partial void OndiaCierreChanging(int value);
    partial void OndiaCierreChanged();
    partial void OnidUsuarioRegistroChanging(int value);
    partial void OnidUsuarioRegistroChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    partial void OnidUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnidUsuarioModificoChanged();
    partial void OnfechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaModificoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public TarjetaXUsuario()
		{
			this._Transaccions = new EntitySet<Transaccion>(new Action<Transaccion>(this.attach_Transaccions), new Action<Transaccion>(this.detach_Transaccions));
			this._Tarjeta = default(EntityRef<Tarjeta>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTarjeta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idTarjeta
		{
			get
			{
				return this._idTarjeta;
			}
			set
			{
				if ((this._idTarjeta != value))
				{
					if (this._Tarjeta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTarjetaChanging(value);
					this.SendPropertyChanging();
					this._idTarjeta = value;
					this.SendPropertyChanged("idTarjeta");
					this.OnidTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string numero
		{
			get
			{
				return this._numero;
			}
			set
			{
				if ((this._numero != value))
				{
					this.OnnumeroChanging(value);
					this.SendPropertyChanging();
					this._numero = value;
					this.SendPropertyChanged("numero");
					this.OnnumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaCierre", DbType="Int NOT NULL")]
		public int diaCierre
		{
			get
			{
				return this._diaCierre;
			}
			set
			{
				if ((this._diaCierre != value))
				{
					this.OndiaCierreChanging(value);
					this.SendPropertyChanging();
					this._diaCierre = value;
					this.SendPropertyChanged("diaCierre");
					this.OndiaCierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioRegistro", DbType="Int NOT NULL")]
		public int idUsuarioRegistro
		{
			get
			{
				return this._idUsuarioRegistro;
			}
			set
			{
				if ((this._idUsuarioRegistro != value))
				{
					this.OnidUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioRegistro = value;
					this.SendPropertyChanged("idUsuarioRegistro");
					this.OnidUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioModifico", DbType="Int")]
		public System.Nullable<int> idUsuarioModifico
		{
			get
			{
				return this._idUsuarioModifico;
			}
			set
			{
				if ((this._idUsuarioModifico != value))
				{
					this.OnidUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioModifico = value;
					this.SendPropertyChanged("idUsuarioModifico");
					this.OnidUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaModifico
		{
			get
			{
				return this._fechaModifico;
			}
			set
			{
				if ((this._fechaModifico != value))
				{
					this.OnfechaModificoChanging(value);
					this.SendPropertyChanging();
					this._fechaModifico = value;
					this.SendPropertyChanged("fechaModifico");
					this.OnfechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TarjetaXUsuario_Transaccion", Storage="_Transaccions", ThisKey="idUsuario,idTarjeta", OtherKey="idUsuario,idTarjeta")]
		public EntitySet<Transaccion> Transaccions
		{
			get
			{
				return this._Transaccions;
			}
			set
			{
				this._Transaccions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tarjeta_TarjetaXUsuario", Storage="_Tarjeta", ThisKey="idTarjeta", OtherKey="idTarjeta", IsForeignKey=true)]
		public Tarjeta Tarjeta
		{
			get
			{
				return this._Tarjeta.Entity;
			}
			set
			{
				Tarjeta previousValue = this._Tarjeta.Entity;
				if (((previousValue != value) 
							|| (this._Tarjeta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tarjeta.Entity = null;
						previousValue.TarjetaXUsuarios.Remove(this);
					}
					this._Tarjeta.Entity = value;
					if ((value != null))
					{
						value.TarjetaXUsuarios.Add(this);
						this._idTarjeta = value.idTarjeta;
					}
					else
					{
						this._idTarjeta = default(int);
					}
					this.SendPropertyChanged("Tarjeta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_TarjetaXUsuario", Storage="_Usuario", ThisKey="idUsuario", OtherKey="idUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.TarjetaXUsuarios.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.TarjetaXUsuarios.Add(this);
						this._idUsuario = value.idUsuario;
					}
					else
					{
						this._idUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.TarjetaXUsuario = this;
		}
		
		private void detach_Transaccions(Transaccion entity)
		{
			this.SendPropertyChanging();
			entity.TarjetaXUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transaccion")]
	public partial class Transaccion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTransaccion;
		
		private System.DateTime _fecha;
		
		private int _idUsuario;
		
		private int _idTarjeta;
		
		private int _idMoneda;
		
		private decimal _montoTotal;
		
		private int _cuotas;
		
		private decimal _montoCuota;
		
		private int _idUsuarioRegistro;
		
		private System.DateTime _fechaRegistro;
		
		private System.Nullable<int> _idUsuarioModifico;
		
		private System.Nullable<System.DateTime> _fechaModifico;
		
		private bool _activo;
		
		private EntitySet<Movimiento> _Movimientos;
		
		private EntityRef<Moneda> _Moneda;
		
		private EntityRef<TarjetaXUsuario> _TarjetaXUsuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTransaccionChanging(int value);
    partial void OnidTransaccionChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OnidUsuarioChanging(int value);
    partial void OnidUsuarioChanged();
    partial void OnidTarjetaChanging(int value);
    partial void OnidTarjetaChanged();
    partial void OnidMonedaChanging(int value);
    partial void OnidMonedaChanged();
    partial void OnmontoTotalChanging(decimal value);
    partial void OnmontoTotalChanged();
    partial void OncuotasChanging(int value);
    partial void OncuotasChanged();
    partial void OnmontoCuotaChanging(decimal value);
    partial void OnmontoCuotaChanged();
    partial void OnidUsuarioRegistroChanging(int value);
    partial void OnidUsuarioRegistroChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    partial void OnidUsuarioModificoChanging(System.Nullable<int> value);
    partial void OnidUsuarioModificoChanged();
    partial void OnfechaModificoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaModificoChanged();
    partial void OnactivoChanging(bool value);
    partial void OnactivoChanged();
    #endregion
		
		public Transaccion()
		{
			this._Movimientos = new EntitySet<Movimiento>(new Action<Movimiento>(this.attach_Movimientos), new Action<Movimiento>(this.detach_Movimientos));
			this._Moneda = default(EntityRef<Moneda>);
			this._TarjetaXUsuario = default(EntityRef<TarjetaXUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTransaccion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTransaccion
		{
			get
			{
				return this._idTransaccion;
			}
			set
			{
				if ((this._idTransaccion != value))
				{
					this.OnidTransaccionChanging(value);
					this.SendPropertyChanging();
					this._idTransaccion = value;
					this.SendPropertyChanged("idTransaccion");
					this.OnidTransaccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuario", DbType="Int NOT NULL")]
		public int idUsuario
		{
			get
			{
				return this._idUsuario;
			}
			set
			{
				if ((this._idUsuario != value))
				{
					if (this._TarjetaXUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidUsuarioChanging(value);
					this.SendPropertyChanging();
					this._idUsuario = value;
					this.SendPropertyChanged("idUsuario");
					this.OnidUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTarjeta", DbType="Int NOT NULL")]
		public int idTarjeta
		{
			get
			{
				return this._idTarjeta;
			}
			set
			{
				if ((this._idTarjeta != value))
				{
					if (this._TarjetaXUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTarjetaChanging(value);
					this.SendPropertyChanging();
					this._idTarjeta = value;
					this.SendPropertyChanged("idTarjeta");
					this.OnidTarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idMoneda", DbType="Int NOT NULL")]
		public int idMoneda
		{
			get
			{
				return this._idMoneda;
			}
			set
			{
				if ((this._idMoneda != value))
				{
					if (this._Moneda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidMonedaChanging(value);
					this.SendPropertyChanging();
					this._idMoneda = value;
					this.SendPropertyChanged("idMoneda");
					this.OnidMonedaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoTotal", DbType="Decimal(18,2) NOT NULL")]
		public decimal montoTotal
		{
			get
			{
				return this._montoTotal;
			}
			set
			{
				if ((this._montoTotal != value))
				{
					this.OnmontoTotalChanging(value);
					this.SendPropertyChanging();
					this._montoTotal = value;
					this.SendPropertyChanged("montoTotal");
					this.OnmontoTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cuotas", DbType="Int NOT NULL")]
		public int cuotas
		{
			get
			{
				return this._cuotas;
			}
			set
			{
				if ((this._cuotas != value))
				{
					this.OncuotasChanging(value);
					this.SendPropertyChanging();
					this._cuotas = value;
					this.SendPropertyChanged("cuotas");
					this.OncuotasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_montoCuota", DbType="Decimal(18,2) NOT NULL")]
		public decimal montoCuota
		{
			get
			{
				return this._montoCuota;
			}
			set
			{
				if ((this._montoCuota != value))
				{
					this.OnmontoCuotaChanging(value);
					this.SendPropertyChanging();
					this._montoCuota = value;
					this.SendPropertyChanged("montoCuota");
					this.OnmontoCuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioRegistro", DbType="Int NOT NULL")]
		public int idUsuarioRegistro
		{
			get
			{
				return this._idUsuarioRegistro;
			}
			set
			{
				if ((this._idUsuarioRegistro != value))
				{
					this.OnidUsuarioRegistroChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioRegistro = value;
					this.SendPropertyChanged("idUsuarioRegistro");
					this.OnidUsuarioRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idUsuarioModifico", DbType="Int")]
		public System.Nullable<int> idUsuarioModifico
		{
			get
			{
				return this._idUsuarioModifico;
			}
			set
			{
				if ((this._idUsuarioModifico != value))
				{
					this.OnidUsuarioModificoChanging(value);
					this.SendPropertyChanging();
					this._idUsuarioModifico = value;
					this.SendPropertyChanged("idUsuarioModifico");
					this.OnidUsuarioModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaModifico", DbType="DateTime")]
		public System.Nullable<System.DateTime> fechaModifico
		{
			get
			{
				return this._fechaModifico;
			}
			set
			{
				if ((this._fechaModifico != value))
				{
					this.OnfechaModificoChanging(value);
					this.SendPropertyChanging();
					this._fechaModifico = value;
					this.SendPropertyChanged("fechaModifico");
					this.OnfechaModificoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit NOT NULL")]
		public bool activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Transaccion_Movimiento", Storage="_Movimientos", ThisKey="idTransaccion", OtherKey="idTransaccion")]
		public EntitySet<Movimiento> Movimientos
		{
			get
			{
				return this._Movimientos;
			}
			set
			{
				this._Movimientos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Moneda_Transaccion", Storage="_Moneda", ThisKey="idMoneda", OtherKey="idMoneda", IsForeignKey=true)]
		public Moneda Moneda
		{
			get
			{
				return this._Moneda.Entity;
			}
			set
			{
				Moneda previousValue = this._Moneda.Entity;
				if (((previousValue != value) 
							|| (this._Moneda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Moneda.Entity = null;
						previousValue.Transaccions.Remove(this);
					}
					this._Moneda.Entity = value;
					if ((value != null))
					{
						value.Transaccions.Add(this);
						this._idMoneda = value.idMoneda;
					}
					else
					{
						this._idMoneda = default(int);
					}
					this.SendPropertyChanged("Moneda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TarjetaXUsuario_Transaccion", Storage="_TarjetaXUsuario", ThisKey="idUsuario,idTarjeta", OtherKey="idUsuario,idTarjeta", IsForeignKey=true)]
		public TarjetaXUsuario TarjetaXUsuario
		{
			get
			{
				return this._TarjetaXUsuario.Entity;
			}
			set
			{
				TarjetaXUsuario previousValue = this._TarjetaXUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TarjetaXUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TarjetaXUsuario.Entity = null;
						previousValue.Transaccions.Remove(this);
					}
					this._TarjetaXUsuario.Entity = value;
					if ((value != null))
					{
						value.Transaccions.Add(this);
						this._idUsuario = value.idUsuario;
						this._idTarjeta = value.idTarjeta;
					}
					else
					{
						this._idUsuario = default(int);
						this._idTarjeta = default(int);
					}
					this.SendPropertyChanged("TarjetaXUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Movimientos(Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.Transaccion = this;
		}
		
		private void detach_Movimientos(Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.Transaccion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Excepcion")]
	public partial class Excepcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idException;
		
		private string _clase;
		
		private string _message;
		
		private string _tipoException;
		
		private System.DateTime _fechaRegistro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidExceptionChanging(int value);
    partial void OnidExceptionChanged();
    partial void OnclaseChanging(string value);
    partial void OnclaseChanged();
    partial void OnmessageChanging(string value);
    partial void OnmessageChanged();
    partial void OntipoExceptionChanging(string value);
    partial void OntipoExceptionChanged();
    partial void OnfechaRegistroChanging(System.DateTime value);
    partial void OnfechaRegistroChanged();
    #endregion
		
		public Excepcion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idException", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idException
		{
			get
			{
				return this._idException;
			}
			set
			{
				if ((this._idException != value))
				{
					this.OnidExceptionChanging(value);
					this.SendPropertyChanging();
					this._idException = value;
					this.SendPropertyChanged("idException");
					this.OnidExceptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clase", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string clase
		{
			get
			{
				return this._clase;
			}
			set
			{
				if ((this._clase != value))
				{
					this.OnclaseChanging(value);
					this.SendPropertyChanging();
					this._clase = value;
					this.SendPropertyChanged("clase");
					this.OnclaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(4000) NOT NULL", CanBeNull=false)]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this.OnmessageChanging(value);
					this.SendPropertyChanging();
					this._message = value;
					this.SendPropertyChanged("message");
					this.OnmessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoException", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string tipoException
		{
			get
			{
				return this._tipoException;
			}
			set
			{
				if ((this._tipoException != value))
				{
					this.OntipoExceptionChanging(value);
					this.SendPropertyChanging();
					this._tipoException = value;
					this.SendPropertyChanged("tipoException");
					this.OntipoExceptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRegistro", DbType="DateTime NOT NULL")]
		public System.DateTime fechaRegistro
		{
			get
			{
				return this._fechaRegistro;
			}
			set
			{
				if ((this._fechaRegistro != value))
				{
					this.OnfechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._fechaRegistro = value;
					this.SendPropertyChanged("fechaRegistro");
					this.OnfechaRegistroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
